server:
  port: 8888
#  ssl:
#    key-store: classpath:config/2213595_www.gbadiea.com.pfx
#    key-store-password: w5D4Ccj4
#    key-password: w5D4Ccj4
#    key-store-type: PKCS12

spring:
  thymeleaf:
    mode : LEGACYHTML5

  datasource:
    name: amis
    url: jdbc:mysql://127.0.0.1:3306/amis?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: amis
    password: amis123
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

  redis:
    host: 127.0.0.1
    port: 6379
    password: amis123
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 12000


mybatis:
  mybatis:
    configuration:
      call-setters-on-nulls: true
  mapper-locations: classpath:config/mapper/*.xml
  type-aliases-package: com.amis.entity

logging:
  level:
       root: info
  config: classpath:config/logback.xml

name: ChenZeXin