server:
  port: 8888

spring:
  datasource:
    name: amis
    url: jdbc:mysql://127.0.0.1:3306/amis?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: amis
    password: amis123
    driver-class-name: com.mysql.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  redis:
    host: 127.0.0.1
    port: 6379
    password: amis123
    jedis:
      pool:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 12000


mybatis:
  mybatis:
    configuration:
      call-setters-on-nulls: true
  mapper-locations: classpath:config/mapper/*.xml
  type-aliases-package: com.amis.entity

logging:
  level:
       root: info
  config: output/config/logback.xml

name: ChenZeXin